CREATE TABLE PESSOA (
	IDPESSOA INT PRIMARY KEY IDENTITY (1,1),
	NOME NVARCHAR (150),
	EMAIL NVARCHAR (100),
	TELEFONE NVARCHAR (20),
	DTNASCIMENTO DATE
)

CREATE TABLE ALUNO(
	IDALUNO INT PRIMARY KEY IDENTITY (1,1),
	RA NVARCHAR (20),
	IDPESSOA INT,

	CONSTRAINT FK_ALUNO_PESSOA FOREIGN KEY (IDPESSOA)
	REFERENCES PESSOA (IDPESSOA)
)

CREATE TABLE FUNCIONÁRIO(
	IDFUNCIONARIO INT PRIMARY KEY IDENTITY(1,1),
	CARGO NVARCHAR (50),
	IDPESSOA INT,

	CONSTRAINT FK_FUNCIONARIO_PESSOA FOREIGN KEY (IDPESSOA)
	REFERENCES PESSOA (IDPESSOA)
)

CREATE TABLE PROFESSOR(
	IDPROFESSOR INT PRIMARY KEY IDENTITY(1,1),
	TITULO NVARCHAR(50),
	IDPESSOA INT,

	CONSTRAINT FK_PROFESSOR_PESSOA FOREIGN KEY (IDPESSOA)
	REFERENCES PESSOA (IDPESSOA)
)

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY IDENTITY(1,1),
	ENDERECO,
)

CREATE TABLE PESSOAENDERECO(
	IDPESSOAENDERECO INT PRIMARY KEY,
	IDPESSOA INT,
	IDENDERECO INT

	
