CREATE TABLE USUARIO (
    COD_USER INT PRIMARY KEY IDENTITY(1,1),
    CPF NVARCHAR(11) unique null,
    NOME NVARCHAR(200),
    DATANAC DATE,
    RG NVARCHAR(8) unique,
    PASSAPORT NVARCHAR(20) unique null,
    STATUS BIT
);


CREATE TABLE ALUNO (
    COD_ALUNO INT PRIMARY KEY IDENTITY(1,1),
    RA INT unique,
    COD_USER INT
);


CREATE TABLE FUNCIONARIO (
    COD_FUNC INT PRIMARY KEY IDENTITY(1,1),
    SALARIO DECIMAL(10,2),
    HORAEXTRA INT,
    COD_USER INT
);


CREATE TABLE DEPARTAMENTO (
    COD_DEPARTAMENTO INT PRIMARY KEY IDENTITY(1,1),
    NOME NVARCHAR(200)
);


CREATE TABLE PROFESSOR (
    COD_PROF INT PRIMARY KEY IDENTITY(1,1),
    GRADUACAO NVARCHAR(200),
    COD_DEPARTAMENTO INT not null,
    COD_FUNC INT
);


CREATE TABLE COORDENADOR (
    COD_COORDENADOR INT PRIMARY KEY IDENTITY(1,1),
    COD_FUNC INT,
    ACRECIMOSALARIAL DECIMAL(10,2) null
);


CREATE TABLE RESPONSAVEL (
    COD_DEPARTAMENTO INT,
    COD_COORDENADOR INT,
    PRIMARY KEY (COD_DEPARTAMENTO, COD_COORDENADOR)
);


CREATE TABLE DEP_PROF (
    COD_DEPPROF INT PRIMARY KEY IDENTITY(1,1),
    COD_PROF INT NULL,
    COD_DEPARTAMENTO INT NULL
);


CREATE TABLE MATERIA (
    COD_MATERIA INT PRIMARY KEY IDENTITY(1,1),
    NOME NVARCHAR(200),
    EXIGENCIAS NVARCHAR(200)
);


CREATE TABLE PROFESSOR_MATERIA (
    COD_PROFESSORMATERIA INT PRIMARY KEY IDENTITY(1,1),
    COD_PROF INT,
    COD_MATERIA INT
);


CREATE TABLE CURSO (
    COD_CURSO INT PRIMARY KEY IDENTITY(1,1),
    NOME NVARCHAR(200),
    COD_DEPARTAMENTO INT
);


CREATE TABLE CURSO_MATERIA (
    COD_CURSOMATERIA INT PRIMARY KEY IDENTITY(1,1),
    COD_CURSO INT,
    COD_MATERIA INT
);


CREATE TABLE ALUNO_MATERIA (
    COD_MATERIAALUNO INT PRIMARY KEY IDENTITY(1,1),
    COD_ALUNO INT,
    COD_MATERIA INT
);


CREATE TABLE CURSO_ALUNO (
    COD_CURSOALUNO INT PRIMARY KEY IDENTITY(1,1),
    COD_CURSO INT,
    COD_ALUNO INT
);


CREATE TABLE SALA (
    COD_SALA INT PRIMARY KEY IDENTITY(1,1),
    CAPACIDADE INT NOT NULL,
    EQUIPAMENTOS NVARCHAR(200) NULL,
    PREDIO INT NOT NULL
);


CREATE TABLE EXAME (
    COD_EXAME INT PRIMARY KEY IDENTITY(1,1),
    EXIGENCIAS NVARCHAR(200) NULL,
    COD_MATERIA INT NOT NULL,
    QTDALUNO INT,
    COD_SALA INT
);


CREATE TABLE ALUNO_EXAME (
    COD_ALUNOEXAME INT PRIMARY KEY IDENTITY(1,1),
    COD_ALUNO INT,
    COD_EXAME INT
);


CREATE TABLE SECAO (
    COD_SECAO INT PRIMARY KEY IDENTITY(1,1),
    HORARIOINICIO DATETIME NOT NULL,
    HORARIOFIMPREVISTO DATETIME ,
    HORARIOFIM DATETIME,
    STATUS BIT
);


CREATE TABLE SECAO_EXAME (
    COD_SECAOEXAME INT PRIMARY KEY IDENTITY(1,1),
    COD_EXAME INT NOT NULL,
    COD_SECAO INT
);


CREATE TABLE SALA_SECAO (
    COD_SALASECAO INT PRIMARY KEY IDENTITY(1,1),
    COD_SALA INT,
    COD_SECAO INT NOT NULL
);



-- USUARIO
ALTER TABLE ALUNO
ADD CONSTRAINT FK_ALUNO_USER
FOREIGN KEY (COD_USER) REFERENCES USUARIO(COD_USER);

ALTER TABLE FUNCIONARIO
ADD CONSTRAINT FK_FUNC_USER
FOREIGN KEY (COD_USER) REFERENCES USUARIO(COD_USER);

-- FUNCIONARIO
ALTER TABLE PROFESSOR
ADD CONSTRAINT FK_PROF_FUNC
FOREIGN KEY (COD_FUNC) REFERENCES FUNCIONARIO(COD_FUNC);

ALTER TABLE COORDENADOR
ADD CONSTRAINT FK_COORD_FUNC
FOREIGN KEY (COD_FUNC) REFERENCES FUNCIONARIO(COD_FUNC);

-- DEPARTAMENTO
ALTER TABLE PROFESSOR
ADD CONSTRAINT FK_PROF_DEP
FOREIGN KEY (COD_DEPARTAMENTO) REFERENCES DEPARTAMENTO(COD_DEPARTAMENTO);

ALTER TABLE CURSO
ADD CONSTRAINT FK_CURSO_DEP
FOREIGN KEY (COD_DEPARTAMENTO) REFERENCES DEPARTAMENTO(COD_DEPARTAMENTO);

-- RESPONSAVEL
ALTER TABLE RESPONSAVEL
ADD CONSTRAINT FK_RESP_DEP
FOREIGN KEY (COD_DEPARTAMENTO) REFERENCES DEPARTAMENTO(COD_DEPARTAMENTO);

ALTER TABLE RESPONSAVEL
ADD CONSTRAINT FK_RESP_COORD
FOREIGN KEY (COD_COORDENADOR) REFERENCES COORDENADOR(COD_COORDENADOR);

-- DEP_PROF
ALTER TABLE DEP_PROF
ADD CONSTRAINT FK_DEPPROF_PROF
FOREIGN KEY (COD_PROF) REFERENCES PROFESSOR(COD_PROF);

ALTER TABLE DEP_PROF
ADD CONSTRAINT FK_DEPPROF_DEP
FOREIGN KEY (COD_DEPARTAMENTO) REFERENCES DEPARTAMENTO(COD_DEPARTAMENTO);

-- PROFESSOR_MATERIA
ALTER TABLE PROFESSOR_MATERIA
ADD CONSTRAINT FK_PROFMAT_PROF
FOREIGN KEY (COD_PROF) REFERENCES PROFESSOR(COD_PROF);

ALTER TABLE PROFESSOR_MATERIA
ADD CONSTRAINT FK_PROFMAT_MAT
FOREIGN KEY (COD_MATERIA) REFERENCES MATERIA(COD_MATERIA);

-- CURSO_MATERIA
ALTER TABLE CURSO_MATERIA
ADD CONSTRAINT FK_CURSMAT_CURSO
FOREIGN KEY (COD_CURSO) REFERENCES CURSO(COD_CURSO);

ALTER TABLE CURSO_MATERIA
ADD CONSTRAINT FK_CURSMAT_MAT
FOREIGN KEY (COD_MATERIA) REFERENCES MATERIA(COD_MATERIA);

-- ALUNO_MATERIA
ALTER TABLE ALUNO_MATERIA
ADD CONSTRAINT FK_ALUMAT_ALUNO
FOREIGN KEY (COD_ALUNO) REFERENCES ALUNO(COD_ALUNO);

ALTER TABLE ALUNO_MATERIA
ADD CONSTRAINT FK_ALUMAT_MAT
FOREIGN KEY (COD_MATERIA) REFERENCES MATERIA(COD_MATERIA);

-- CURSO_ALUNO
ALTER TABLE CURSO_ALUNO
ADD CONSTRAINT FK_CURALUNO_CURSO
FOREIGN KEY (COD_CURSO) REFERENCES CURSO(COD_CURSO);

ALTER TABLE CURSO_ALUNO
ADD CONSTRAINT FK_CURALUNO_ALUNO
FOREIGN KEY (COD_ALUNO) REFERENCES ALUNO(COD_ALUNO);

-- EXAME
ALTER TABLE EXAME
ADD CONSTRAINT FK_EXAME_MAT
FOREIGN KEY (COD_MATERIA) REFERENCES MATERIA(COD_MATERIA);

ALTER TABLE EXAME
ADD CONSTRAINT FK_EXAME_SALA
FOREIGN KEY (COD_SALA) REFERENCES SALA(COD_SALA);

-- ALUNO_EXAME
ALTER TABLE ALUNO_EXAME
ADD CONSTRAINT FK_ALUEX_ALUNO
FOREIGN KEY (COD_ALUNO) REFERENCES ALUNO(COD_ALUNO);

ALTER TABLE ALUNO_EXAME
ADD CONSTRAINT FK_ALUEX_EXAME
FOREIGN KEY (COD_EXAME) REFERENCES EXAME(COD_EXAME);

-- SECAO_EXAME
ALTER TABLE SECAO_EXAME
ADD CONSTRAINT FK_SECEX_EXAME
FOREIGN KEY (COD_EXAME) REFERENCES EXAME(COD_EXAME);

ALTER TABLE SECAO_EXAME
ADD CONSTRAINT FK_SECEX_SECAO
FOREIGN KEY (COD_SECAO) REFERENCES SECAO(COD_SECAO);

-- SALA_SECAO
ALTER TABLE SALA_SECAO
ADD CONSTRAINT FK_SALSEC_SALA
FOREIGN KEY (COD_SALA) REFERENCES SALA(COD_SALA);

ALTER TABLE SALA_SECAO
ADD CONSTRAINT FK_SALSEC_SECAO
FOREIGN KEY (COD_SECAO) REFERENCES SECAO(COD_SECAO);




--populando

INSERT INTO USUARIO (CPF, NOME, DATANAC, RG, PASSAPORT, STATUS) VALUES
('11111111111', 'Joao Silva', '2000-01-10', '12345678', 'P001', 1),
('22222222222', 'Maria Souza', '1999-05-20', '23456789', 'P002', 1),
('33333333333', 'Carlos Lima', '1985-07-15', '34567890', 'P003', 1),
('44444444444', 'Ana Costa', '1990-03-12', '45678901', 'P004', 1),
('55555555555', 'Lucas Alves', '1988-11-25', '56789012', 'P005', 1),
('66666666666', 'Fernanda Rocha', '1995-09-30', '67890123', 'P006', 1),
('77777777777', 'Ricardo Mendes', '1982-02-18', '78901234', 'P007', 1),
('88888888888', 'Juliana Pereira', '1991-04-22', '89012345', 'P008', 1),
('99999999999', 'Bruno Carvalho', '1987-08-10', '90123456', 'P009', 1),
('10101010101', 'Patricia Gomes', '1993-12-05', '01234567', 'P010', 1),
('12121212121', 'Eduardo Martins', '1984-06-17', '11223344', 'P011', 1),
('13131313131', 'Camila Ribeiro', '1996-09-29', '22334455', 'P012', 1);

INSERT INTO ALUNO (RA, COD_USER) VALUES
(1001, 1),
(1002, 2),
(1003, 3),
(1004, 4),
(1005, 5);

INSERT INTO FUNCIONARIO (SALARIO, HORAEXTRA, COD_USER) VALUES
(3000, 10, 5),
(3500, 5, 6),
(4000, 8, 7),
(4500, 12, 8),
(5000, 6, 10),
(3000, 6, 11),
(2000, 6, 12);

INSERT INTO DEPARTAMENTO (NOME) VALUES
('TI'),
('Engenharia'),
('Administracao'),
('Saude'),
('Direito');

INSERT INTO PROFESSOR (GRADUACAO, COD_DEPARTAMENTO, COD_FUNC) VALUES
('Mestrado', 1, 1),
('Doutorado', 2, 2),
('Especialista', 3, 3),
('Mestrado', 4, 4),
('Doutorado', 5, 5);

INSERT INTO COORDENADOR (COD_FUNC, ACRECIMOSALARIAL) VALUES
(1, 500),
(2, 600),
(3, 700),
(4, 800),
(5, 900);


INSERT INTO RESPONSAVEL (COD_DEPARTAMENTO, COD_COORDENADOR) VALUES
(1,1),
(2,2),
(3,3),
(4,4),
(5,5);

INSERT INTO DEP_PROF (COD_PROF, COD_DEPARTAMENTO) VALUES
(1,1),
(2,2),
(3,3),
(4,4),
(5,5);


INSERT INTO MATERIA (NOME, EXIGENCIAS) VALUES
('Banco de Dados', 'SQL basico'),
('Programacao', 'Logica'),
('Redes', 'Conhecimento basico'),
('Engenharia Software', 'UML'),
('Seguranca', 'Criptografia');

INSERT INTO PROFESSOR_MATERIA (COD_PROF, COD_MATERIA) VALUES
(1,1),
(2,2),
(3,3),
(4,4),
(5,5);

INSERT INTO CURSO (NOME, COD_DEPARTAMENTO) VALUES
('ADS', 1),
('Engenharia Civil', 2),
('Administracao Geral', 3),
('Enfermagem', 4),
('Direito Penal', 5);

INSERT INTO CURSO_MATERIA (COD_CURSO, COD_MATERIA) VALUES
(1,1),
(2,2),
(3,3),
(4,4),
(5,5);

INSERT INTO ALUNO_MATERIA (COD_ALUNO, COD_MATERIA) VALUES
(1,1),
(2,2),
(3,3),
(4,4),
(5,5);

INSERT INTO CURSO_ALUNO (COD_CURSO, COD_ALUNO) VALUES
(1,1),
(2,2),
(3,3),
(4,4),
(5,5);

INSERT INTO SALA (CAPACIDADE, EQUIPAMENTOS, PREDIO) VALUES
(30, 'Projetor', 1),
(40, 'Computadores', 1),
(25, 'Quadro', 2),
(35, 'Ar condicionado', 2),
(50, 'Laboratorio', 3);

INSERT INTO EXAME (EXIGENCIAS, COD_MATERIA, QTDALUNO, COD_SALA) VALUES
('Prova escrita', 1, 30, 1),
('Prova pratica', 2, 25, 2),
('Prova oral', 3, 20, 3),
('Trabalho', 4, 35, 4),
('Seminario', 5, 40, 5);

INSERT INTO ALUNO_EXAME (COD_ALUNO, COD_EXAME) VALUES
(1,1),
(2,2),
(3,3),
(4,4),
(5,5);

INSERT INTO SECAO (HORARIOINICIO, HORARIOFIMPREVISTO, HORARIOFIM, STATUS) VALUES
(GETDATE(), DATEADD(HOUR,2,GETDATE()), NULL, 1),
(GETDATE(), DATEADD(HOUR,2,GETDATE()), NULL, 1),
(GETDATE(), DATEADD(HOUR,2,GETDATE()), NULL, 1),
(GETDATE(), DATEADD(HOUR,2,GETDATE()), NULL, 1),
(GETDATE(), DATEADD(HOUR,2,GETDATE()), NULL, 1);

INSERT INTO SECAO_EXAME (COD_EXAME, COD_SECAO) VALUES
(1,1),
(2,2),
(3,3),
(4,4),
(5,5);

INSERT INTO SALA_SECAO (COD_SALA, COD_SECAO) VALUES
(1,1),
(2,2),
(3,3),
(4,4),
(5,5);






--LISTAR USUARIOS ATIVOS
SELECT NOME, CPF,DATANAC FROM USUARIO WHERE STATUS = 1






--LISTAR OS ALUNOS
SELECT US.NOME AS ALUNOS, AL.RA, US.CPF FROM ALUNO AL
LEFT JOIN USUARIO US ON AL.COD_USER = US.COD_USER







--MOSTRA OQ CADA ALUNO TA CURSANDO
SELECT US.NOME, AL.RA, C.NOME AS CURSO FROM ALUNO AL
LEFT JOIN USUARIO US ON AL.COD_USER = US.COD_USER
LEFT JOIN CURSO_ALUNO CA ON AL.COD_ALUNO = CA.COD_ALUNO
LEFT JOIN CURSO C ON CA.COD_CURSO = C.COD_CURSO







--ALUNOS POR CURSO
SELECT C.NOME, COUNT(CA.COD_ALUNO) AS QTD_ALUNOS FROM CURSO C
INNER JOIN CURSO_ALUNO CA ON  CA.COD_CURSO = C.COD_CURSO
GROUP BY C.NOME;




--MOSTRAR OS COORDENADORES E SEUS DEPARTAMENTOS
SELECT FUNC.COD_FUNC, US.NOME, D.NOME AS DEPARTAMENTO FROM COORDENADOR C
LEFT JOIN FUNCIONARIO FUNC ON C.COD_FUNC = FUNC.COD_FUNC
LEFT JOIN USUARIO US ON US.COD_USER = FUNC.COD_USER
LEFT JOIN RESPONSAVEL RES ON RES.COD_COORDENADOR = C.COD_COORDENADOR
LEFT JOIN DEPARTAMENTO D ON D.COD_DEPARTAMENTO = RES.COD_DEPARTAMENTO



