CREATE TABLE HOSPITAL (
	CODHOSPITAL INT PRIMARY KEY IDENTITY (1,1),
	NOME NVARCHAR(250),
	ENDERECO NVARCHAR(200),
	TELEFONE NVARCHAR(20)
)

CREATE TABLE LABORATORIO (
	CODLAB INT PRIMARY KEY IDENTITY (1,1),
	NOME NVARCHAR(250),
	ENDERECO NVARCHAR(200),
	TELEFONE NVARCHAR(20)
)

CREATE TABLE AMBULATORIO (
	CODAMBU INT PRIMARY KEY IDENTITY (1,1),
	NOME NVARCHAR(250),
	LOCALIZACAO NVARCHAR(200),
	CODHOSPITAL INT
	CONSTRAINT FK_AMBULATORIO_HOSPITAL FOREIGN KEY(CODHOSPITAL)
	REFERENCES HOSPITAL(CODHOSPITAL)
)

CREATE TABLE PACIENTE (
	CODPACIENTE INT PRIMARY KEY IDENTITY (1,1),
	NOME NVARCHAR(250),
	CPF NVARCHAR(11),
	DTNASC DATE,
	TELEFONE NVARCHAR(20),
	CODAMBU INT
	CONSTRAINT FK_PACIENTE_AMBULATORIO FOREIGN KEY(CODAMBU)
	REFERENCES AMBULATORIO(CODAMBU)
)

CREATE TABLE MEDICO (
	CODMEDICO INT PRIMARY KEY IDENTITY (1,1),
	NOME NVARCHAR(250),
	CRM NVARCHAR(9),
	ESPECIALIDADE NVARCHAR(50),
	CODHOSPITAL INT
	CONSTRAINT FK_MEDICO_HOSPITAL FOREIGN KEY(CODHOSPITAL)
	REFERENCES HOSPITAL(CODHOSPITAL)
)

CREATE TABLE DIAGNOSTICO(
	CODDIAG INT PRIMARY KEY IDENTITY (1,1),
	DESCRICAO NVARCHAR(400),
	DTDIAG DATE,
	CODPACIENTE INT 
	CONSTRAINT FK_DIAGNOSTICO_PACIENTE FOREIGN KEY(CODPACIENTE)
	REFERENCES PACIENTE(CODPACIENTE)
)

CREATE TABLE PESSOALDEAPOIO (
	CODPESSOAL INT PRIMARY KEY IDENTITY (1,1),
	NOME NVARCHAR(250),
	FUNCAO NVARCHAR(100),
	TELEFONE NVARCHAR(20),
	CODAMBU INT 
	CONSTRAINT FK_PESSOALDEAPOIO_AMBULATORIO FOREIGN KEY(CODAMBU)
	REFERENCES AMBULATORIO(CODAMBU)
)

CREATE TABLE EXAME(
	CODEXAME INT PRIMARY KEY IDENTITY (1,1),
	TIPOEXAME NVARCHAR(200),
	DTEXAME DATE,
	RESULTADO NVARCHAR(200),
	CODPACIENTE INT,
	CODLAB INT
	CONSTRAINT FK_EXAME_PACIENTE FOREIGN KEY(CODPACIENTE)
	REFERENCES PACIENTE(CODPACIENTE),
	CONSTRAINT FK_EXAME_LABORATORIO FOREIGN KEY(CODLAB)
	REFERENCES LABORATORIO(CODLAB)
)

CREATE TABLE MEDICO_PACIENTE(
	CODCONSULTA INT PRIMARY KEY IDENTITY (1,1),
	CODMEDICO INT,
	CODPACIENTE INT,
	DTCONSULTA DATE
	CONSTRAINT FK_CONSULTA_MEDICO FOREIGN KEY(CODMEDICO)
	REFERENCES MEDICO(CODMEDICO),
	CONSTRAINT FK_CONSULTA_PACIENTE FOREIGN KEY(CODPACIENTE)
	REFERENCES PACIENTE(CODPACIENTE)	
)

CREATE TABLE HOSPITAL_LABORATORIO(
	CODSOLICITACAO INT PRIMARY KEY IDENTITY (1,1),
	CODHOSPITAL INT,
	CODLAB INT,
	DTSOLICITACAO DATE
	CONSTRAINT FK_SOLICITACAO_HOSPITAL FOREIGN KEY(CODHOSPITAL)
	REFERENCES HOSPITAL(CODHOSPITAL),
	CONSTRAINT FK_SOLICITACAO_LABORATORIO FOREIGN KEY(CODLAB)
	REFERENCES LABORATORIO(CODLAB)
)

INSERT INTO HOSPITAL (NOME, ENDERECO, TELEFONE) VALUES
('Hospital Santa Branca', 'Rua Dr. Arnaldo Bittencourt', '987654321'),
('Hospital São Camilo de Lellis', 'Rua Professor Joaquim de Morais', '912345678'),
('Hospital Beneficência do Vale', 'Avenida Marechal Deodoro da Fonseca', '922334455'),
('Hospital Metropolitano Central', 'Rua Dona Maria José', '999887766'),
('Hospital Sagrada Esperança', 'Avenida Rio Branco', '955443322')

SELECT * FROM HOSPITAL

INSERT INTO LABORATORIO (NOME, ENDERECO, TELEFONE) VALUES
('Centro de Diagnósticos Vitalab', 'Rua Sete de Setembro', '911223344'),
('Laboratório Sangue Bom', 'Rua das Palmeiras', '988776655'),
('Análises Clínicas Previna', 'Rua Vereador José Antunes', '933445566'),
('Análises Clínicas Previna', 'Rua Santa Catarina', '977665544'),
('Instituto ImmunoScan', 'Avenida Pe. Manoel', '944556677')

SELECT * FROM LABORATORIO

INSERT INTO AMBULATORIO (NOME, LOCALIZACAO, CODHOSPITAL) VALUES
('Ambulatório Geral', 'Bloco A', 1),
('Ambulatório Infantil', 'Bloco B', 2),
('Ambulatório Ortopédico', 'Bloco C', 3),
('Ambulatório Cardiológico', 'Bloco D', 4),
('Ambulatório Clínico', 'Bloco E', 5)

SELECT * FROM AMBULATORIO

INSERT INTO PACIENTE (NOME, CPF, DTNASC, TELEFONE, CODAMBU) VALUES
('Murilo', '12312312312', '2012-03-23', '12996036493', 2),
('Sarah', '49223751802', '2006-06-27', '12996238886', 1),
('Fabiano', '55611632807', '2005-03-13', '12991676020', 3),
('Reginaldo', '43503005858', '1998-08-29', '12991998303', 5),
('Luiz', '53317361816', '2005-02-11', '12996723803', 5)

SELECT * FROM PACIENTE

INSERT INTO MEDICO (NOME, CRM, ESPECIALIDADE, CODHOSPITAL) VALUES
('Dr. Ricardo Alves', '123456', 'Clínico Geral', 1),
('Dra. Fernanda Lima', '234567', 'Cardiologia', 2),
('Dr. Paulo Mendes', '345678', 'Ortopedia', 3),
('Dra. Juliana Rocha', '456789', 'Pediatria', 4),
('Dr. Eduardo Martins', '567890', 'Neurologia', 5)

SELECT * FROM MEDICO

INSERT INTO DIAGNOSTICO (DESCRICAO, DTDIAG, CODPACIENTE) VALUES
('Gripe', '2026-01-01', 1),
('Dor abdominal forte', '2026-01-02', 2),
('Fratura no braço', '2026-01-03', 3),
('Infecção viral', '2026-01-04', 4),
('Enxaqueca', '2026-01-05', 5)

SELECT * FROM DIAGNOSTICO

INSERT INTO PESSOALDEAPOIO (NOME, FUNCAO, TELEFONE, CODAMBU) VALUES
('Juliana Costa', 'Enfermeira', '910293847', 1),
('Pedro Henrique', 'Auxiliar', '966550011', 2),
('Camila Rocha', 'Técnica em Imobilização', '956473829', 3),
('Rafael Lima', 'Auxiliar Cardiológico', '909182736', 4),
('Beatriz Souza', 'Recepcionista Clínica', '945362718', 5)

SELECT * FROM PESSOALDEAPOIO

INSERT INTO EXAME (TIPOEXAME, DTEXAME, RESULTADO, CODPACIENTE, CODLAB) VALUES
('Hemograma', '2026-02-01', 'Alteração compatível com gripe', 1, 1),
('Ultrassom abdominal', '2026-02-02', 'Inflamação detectada', 2, 2),
('Raio-X do braço', '2026-02-03', 'Fratura confirmada', 3, 3),
('Exame de sangue', '2026-02-04', 'Infecção viral detectada', 4, 4),
('Ressonância magnética', '2026-02-05', 'Sem alterações estruturais', 5, 5)

SELECT * FROM EXAME

INSERT INTO MEDICO_PACIENTE (CODMEDICO, CODPACIENTE, DTCONSULTA) VALUES
(4, 1, '2026-03-01'), 
(1, 2, '2026-03-02'), 
(3, 3, '2026-03-03'), 
(1, 4, '2026-03-04'), 
(5, 5, '2026-03-05')

SELECT * FROM MEDICO_PACIENTE

INSERT INTO HOSPITAL_LABORATORIO (CODHOSPITAL, CODLAB, DTSOLICITACAO) VALUES
(1, 1, '2026-03-10'),
(2, 2, '2026-03-11'),
(3, 3, '2026-03-12'),
(4, 4, '2026-03-13'),
(5, 5, '2026-03-14')

SELECT * FROM HOSPITAL_LABORATORIO

SELECT P.NOME PACIENTE, D.DESCRICAO DIAGNOSTICO, D.DTDIAG DATA_DIAGNOSTICO
FROM PACIENTE P
INNER JOIN DIAGNOSTICO D ON P.CODPACIENTE = D.CODPACIENTE

SELECT A.NOME AMBULATORIO, A.LOCALIZACAO, P.NOME PESSOAL, P.FUNCAO, H.NOME HOSPITAL
FROM AMBULATORIO A
INNER JOIN PESSOALDEAPOIO P ON A.CODAMBU = P.CODAMBU
INNER JOIN HOSPITAL H ON A.CODHOSPITAL = H.CODHOSPITAL;

SELECT  P.NOME PACIENTE, M.NOME MEDICO,D.DESCRICAO DIAGNOSTICO, E.TIPOEXAME EXAME, E.RESULTADO RESULTADO
FROM PACIENTE P
INNER JOIN MEDICO_PACIENTE MP ON P.CODPACIENTE = MP.CODPACIENTE
INNER JOIN MEDICO M ON MP.CODMEDICO = M.CODMEDICO
INNER JOIN DIAGNOSTICO D ON P.CODPACIENTE = D.CODPACIENTE
INNER JOIN EXAME E ON P.CODPACIENTE = E.CODPACIENTE

