CREATE TABLE PACIENTE (
	CODPACIENTE INT PRIMARY KEY IDENTITY(1,1),
	NOME NVARCHAR (100),
	RG NVARCHAR (15),
	CPF NVARCHAR (11),
	SEXO CHAR (1),
	DATANASC DATE,
	TELEFONE NVARCHAR (15),
)


CREATE TABLE TIPOCONVENIO(
	CODTIPOCONVENIO INT PRIMARY KEY IDENTITY(1,1),
	NOMECONVENIO NVARCHAR(100),
	DESCRICAO NVARCHAR (200),
	VALOR DECIMAL(10, 2)
)


CREATE TABLE CONVENIO(
	CODCONVENIO INT PRIMARY KEY IDENTITY(1,1),
	DESCRICAO NVARCHAR (200),
	CODTIPOCONVENIO INT,

	CONSTRAINT FK_CONVENIO_TIPOCONVENIO FOREIGN KEY (CODTIPOCONVENIO)
	REFERENCES TIPOCONVENIO (CODTIPOCONVENIO)
)


CREATE TABLE PACIENTECONVENIO (
	CODPACIENTECONVENIO INT PRIMARY KEY IDENTITY(1,1),
	CODPACIENTE INT,
	CODCONVENIO INT,

	CONSTRAINT FK_PACIENTECONVENIO_PACIENTE FOREIGN KEY (CODPACIENTE)
	REFERENCES PACIENTE (CODPACIENTE),

	CONSTRAINT FK_PACIENTECONVENIO_CONVENIO FOREIGN KEY (CODCONVENIO)
	REFERENCES CONVENIO (CODCONVENIO)

)


CREATE TABLE MEDICO(
	CRM INT PRIMARY KEY,
	NOME NVARCHAR (150),
	TELEFONE NVARCHAR (15),
	ESPECIALIDADE NVARCHAR (100)
)


CREATE TABLE CONSULTA(
	CODCONSULTA INT PRIMARY KEY IDENTITY(1,1),
	DATACONSULTA DATE,
	HORARIOCONSULTA TIME,
	CODPACIENTE INT,
	CRM INT,

	CONSTRAINT FK_COSULTA_PACIENTE FOREIGN KEY (CODPACIENTE)
	REFERENCES PACIENTE (CODPACIENTE),

	CONSTRAINT FK_CONSULTA_MEDICO FOREIGN KEY (CRM)
	REFERENCES MEDICO (CRM)



)
