CREATE TABLE COR (
	CODCOR INT PRIMARY KEY,
	DESCRICAO NVARCHAR (100)
)


CREATE TABLE FABRICANTE(
	CODFABRICANTE INT PRIMARY KEY,
	DESCRICAO NVARCHAR (200)
)


CREATE TABLE PROPRIETARIO (
	CODPROPRIETARIO INT PRIMARY KEY,
	NOMEPROP NVARCHAR (150),
	HABILITACAO NVARCHAR (11) NOT NULL UNIQUE
)


CREATE TABLE MODELO(
	CODMODELO INT PRIMARY KEY,
	DESCRICAO NVARCHAR (200),
	CODFABRICANTE INT,

	CONSTRAINT FK_MODELO_FABRICANTE FOREIGN KEY (CODFABRICANTE)
	REFERENCES FABRICANTE (CODFABRICANTE)
)


CREATE TABLE VEICULO (
	CHASSI INT PRIMARY KEY, 
	PLACA NVARCHAR (100),
	ANOMODELO INT,
	ANOFABRICANTE INT,
	CODMODELO INT,
	CODCOR INT,

	CONSTRAINT FK_MODELO_VEICULO FOREIGN KEY (CODMODELO)
	REFERENCES MODELO (CODMODELO),

	CONSTRAINT FK_COR_VEICULO FOREIGN KEY (CODCOR)
	REFERENCES COR (CODCOR)
)


CREATE TABLE PROPVEICULO (
	CODPROPVEIC INT PRIMARY KEY,
	CODPROPRIETARIO INT,
	CHASSI INT,

	CONSTRAINT FK_PROPRIETARIO_PROPVEICULO FOREIGN KEY (CODPROPRIETARIO)
	REFERENCES PROPRIETARIO (CODPROPRIETARIO),

	CONSTRAINT FK_VEICULO_PROPVEICULO FOREIGN KEY (CHASSI)
	REFERENCES VEICULO (CHASSI)
)
