CREATE TABLE PESSOA (
	CODPESSOA INT PRIMARY KEY IDENTITY (1,1),
	NOME NVARCHAR (100),
	DATANASCIMENTO DATE
)

CREATE TABLE FUNCIONARIO (
	REGISTROFUNC INT PRIMARY KEY,
	CODCONJUGUE INT,
	CODPESSOA INT,

	CONSTRAINT FK_FUNCIONARIO_PESSOA FOREIGN KEY (CODPESSOA)
	REFERENCES PESSOA (CODPESSOA),

	CONSTRAINT FK_FUNCIONARIO_CONJUGUE FOREIGN KEY (CODCONJUGUE)
	REFERENCES FUNCIONARIO (REGISTROFUNC)
)

CREATE TABLE DEPENDENTES (
	CODPESSOA INT,
	CODDEPENDENTE INT PRIMARY KEY IDENTITY (1,1),
	REGISTROFUNC INT,

	CONSTRAINT FK_DEPENDENTES_PESSOA FOREIGN KEY (CODPESSOA)
	REFERENCES PESSOA (CODPESSOA),

	CONSTRAINT FK_DEPENDENTES_FUNCIONARIO FOREIGN KEY (REGISTROFUNC)
	REFERENCES FUNCIONARIO (REGISTROFUNC)
)
