CREATE TABLE DEPARTAMENTO(
	IDDEPARTAMENTO INT PRIMARY KEY IDENTITY(1,1),
	NOME NVARCHAR (100),
	DESCRICAO NVARCHAR(200)
)
CREATE TABLE CARGO(
	IDCARGO INT PRIMARY KEY IDENTITY(1,1),
	NOME NVARCHAR(100),
	DESCRICAO NVARCHAR(200)
)
CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY IDENTITY(1,1),
	ENDERECO NVARCHAR(200)
)
CREATE TABLE FUNCIONARIO(
	IDFUNCIONARIO INT PRIMARY KEY IDENTITY(1,1),
	NOME NVARCHAR(150),
	TELEFONE NVARCHAR (20),
	EMAIL NVARCHAR (50),
	DTNASCIMENTO DATE,
	CPF NVARCHAR (15) UNIQUE,
	IDCARGO INT,
	IDDEPARTAMENTO INT,

	CONSTRAINT FK_FUNCIONARIO_CARGO FOREIGN KEY (IDCARGO)
	REFERENCES CARGO (IDCARGO),

	CONSTRAINT FK_FUNCIONARIO_DEPARTAMENTO FOREIGN KEY (IDDEPARTAMENTO)
	REFERENCES DEPARTAMENTO (IDDEPARTAMENTO)
)
CREATE TABLE FUNCIONARIOENDERECO(
	IDFUNCIONARIOENDERECO INT PRIMARY KEY IDENTITY(1,1),
	IDFUNCIONARIO INT,
	IDENDERECO INT,

	CONSTRAINT FK_FUNCIONARIOENDERECO_FUNCIONARIO FOREIGN KEY (IDFUNCIONARIO)
	REFERENCES FUNCIONARIO (IDFUNCIONARIO),

	CONSTRAINT FK_FUNCIONARIOENDERECO_ENDERECO FOREIGN KEY (IDENDERECO)
	REFERENCES ENDERECO (IDENDERECO)
)
