CREATE TABLE PESSOA (
	IDPESSOA INT PRIMARY KEY IDENTITY (1,1),
	NOME NVARCHAR (150),
	EMAIL NVARCHAR (100),
	TELEFONE NVARCHAR (20),
	DTNASCIMENTO DATE
)

CREATE TABLE ALUNO(
	IDALUNO INT PRIMARY KEY IDENTITY (1,1),
	RA NVARCHAR (20),
	IDPESSOA INT,

	CONSTRAINT FK_ALUNO_PESSOA FOREIGN KEY (IDPESSOA)
	REFERENCES PESSOA (IDPESSOA)
)

CREATE TABLE FUNCIONÁRIO(
	IDFUNCIONARIO INT PRIMARY KEY IDENTITY(1,1),
	CARGO NVARCHAR (50),
	IDPESSOA INT,

	CONSTRAINT FK_FUNCIONARIO_PESSOA FOREIGN KEY (IDPESSOA)
	REFERENCES PESSOA (IDPESSOA)
)

CREATE TABLE PROFESSOR(
	IDPROFESSOR INT PRIMARY KEY IDENTITY(1,1),
	TITULO NVARCHAR(50),
	IDPESSOA INT,

	CONSTRAINT FK_PROFESSOR_PESSOA FOREIGN KEY (IDPESSOA)
	REFERENCES PESSOA (IDPESSOA)
)

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY IDENTITY(1,1),
	ENDERECO NVARCHAR (200)
)

CREATE TABLE PESSOAENDERECO(
	IDPESSOAENDERECO INT PRIMARY KEY IDENTITY (1,1),
	IDPESSOA INT,
	IDENDERECO INT,

	CONSTRAINT FK_PESSOAENDERECO_PESSOA FOREIGN KEY (IDPESSOA)
	REFERENCES PESSOA (IDPESSOA),

	CONSTRAINT FK_PESSOAENDERECO_ENDERECO FOREIGN KEY (IDENDERECO)
	REFERENCES ENDERECO (IDENDERECO)
)

CREATE TABLE AUTOR (
	IDAUTOR INT PRIMARY KEY IDENTITY(1,1),
	IDPESSOA INT,

	CONSTRAINT FK_AUTOR_PESSOA FOREIGN KEY (IDPESSOA)
	REFERENCES PESSOA (IDPESSOA)
)

CREATE TABLE LIVRO(
	IDLIVRO INT PRIMARY KEY IDENTITY (1,1),
	TITULO NVARCHAR(100),
	ANOPUBLI DATE,
	GENERO NVARCHAR(100),
	NUMPAG INT,
	DISPONIVEL CHAR,
	IDAUTOR INT,

	CONSTRAINT FK_LIVRO_AUTOR FOREIGN KEY (IDAUTOR)
	REFERENCES AUTOR (IDAUTOR)
)

CREATE TABLE EDITORA(
	IDEDITORA INT PRIMARY KEY IDENTITY(1,1),
	NOME NVARCHAR(100)
)

CREATE TABLE LIVROEDITORA(
	IDLIVROEDITORA INT PRIMARY KEY IDENTITY(1,1),
	IDLIVRO INT,
	IDEDITORA INT,

	CONSTRAINT FK_LIVROEDITORA_LIVRO FOREIGN KEY (IDLIVRO)
	REFERENCES LIVRO (IDLIVRO),

	CONSTRAINT FK_LIVROEDITORA_EDITORA FOREIGN KEY (IDEDITORA)
	REFERENCES EDITORA (IDEDITORA)
)

CREATE TABLE EMPRESTIMO (
	IDEMPRESTIMO INT PRIMARY KEY IDENTITY(1,1),
	IDLIVRO INT,
	IDPESSOA INT,
	DTEMPRESTIMO DATE,
	DTDEVOLUCAO DATE, 
	DTDEVOLVIDO DATE,

	CONSTRAINT FK_EMPRESTIMO_LIVRO FOREIGN KEY (IDLIVRO)
	REFERENCES LIVRO (IDLIVRO),

	CONSTRAINT FK_EMPRESTIMO_PESSOA FOREIGN KEY (IDPESSOA)
	REFERENCES PESSOA (IDPESSOA)
)


	
