CREATE TABLE PROFESSOR (
	CODPROFESSOR INT PRIMARY KEY IDENTITY(1,1),
	NOME NVARCHAR (200),
	EMAIL NVARCHAR(1500),
	CPF NVARCHAR (11),
	RG NVARCHAR (15)
)

SELECT * FROM PROFESSOR
INSERT INTO PROFESSOR (NOME, EMAIL, CPF, RG)
VALUES ('SARAH', 'SARAH@FATEC', '123457', 'RG')


CREATE TABLE PESSOAS(
	CODPESSOA INT PRIMARY KEY IDENTITY(1,1),
	NOME NVARCHAR(100),
	EMAIL NVARCHAR(100)
)

INSERT INTO PESSOAS (NOME, EMAIL)
SELECT NOME, EMAIL FROM PROFESSOR

SELECT * FROM PESSOAS 

CREATE TABLE VENDAS (
	

)
