CREATE TABLE PRODUTO (
	IDPRODUTO INT PRIMARY KEY IDENTITY (1,1),
	NOME NVARCHAR (150),
	DESCRICAO NVARCHAR (200),
	CATEGORIA NVARCHAR (100),
	PRECO DECIMAL (10,2),
	ESTOQUE INT
)


CREATE TABLE CLIENTE (
	IDCLIENTE INT PRIMARY KEY IDENTITY(1,1),
	NOME NVARCHAR (200),
	TELEFONE NVARCHAR (20),
	EMAIL NVARCHAR (50),
	DTNASCIMENTO DATE
)


CREATE TABLE ENDERECO(
	CODENDERECO INT PRIMARY KEY,
	ENDERECORESIDENCIA NVARCHAR (250) UNIQUE,
	ENDERECOENTREGA NVARCHAR (250)
)


CREATE TABLE CLIENTE_ENDERECO(
	CODCLIENTEENDERECO INT PRIMARY KEY IDENTITY(1,1),
	CODENDERECO INT,
	IDCLIENTE INT,

	CONSTRAINT FK_CLIENTEENDERECO_ENDERCO FOREIGN KEY (CODENDERECO)
	REFERENCES ENDERECO (CODENDERECO),

	CONSTRAINT FK_CLIENTEENDERECO_CLIENTE FOREIGN KEY (IDCLIENTE)
	REFERENCES CLIENTE (IDCLIENTE)
)


CREATE TABLE PEDIDO(
	IDPEDIDO INT PRIMARY KEY IDENTITY(1,1),
	IDCLIENTE INT,
	DTPEDIDO DATE,
	DTPREVISAOENTREGA DATE,
	DTENTREGUE DATE,
	SATUS NVARCHAR(100)

	CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (IDCLIENTE)
	REFERENCES CLIENTE (IDCLIENTE),
)

CREATE TABLE PRODUTO_PEDIDO(
	CODPRODPED INT PRIMARY KEY,
	QUANTIDADE INT,
	VALORVENDA DECIMAL (10,2),
	IDPRODUTO INT,
	IDPEDIDO INT,
	
	CONSTRAINT FK_PRODPED_PRODUTO FOREIGN KEY (IDPRODUTO)
	REFERENCES PRODUTO (IDPRODUTO),

	CONSTRAINT FK_PRODPED_PEDIDO FOREIGN KEY (IDPEDIDO)
	REFERENCES PEDIDO (IDPEDIDO),
	
)

CREATE TABLE VENDA(
	CODVENDA INT PRIMARY KEY,
	FORMAPAGAMENTO NVARCHAR (100),
	IDPEDIDO INT,

	CONSTRAINT FK_VENDA_PEDIDO FOREIGN KEY (IDPEDIDO)
	REFERENCES PEDIDO (IDPEDIDO)
)
