CREATE TABLE PESSOA (
	CODPESSOA INT PRIMARY KEY IDENTITY(1,1),
	NOME NVARCHAR(100),
	CPF NVARCHAR(11),
	RG NVARCHAR (15),
	DTNASC DATE
)


CREATE TABLE VENDEDOR (
	CODVENDEDOR INT PRIMARY KEY,
	CODPESSOA INT,

	CONSTRAINT FK_VENDEDOR_PESSOA FOREIGN KEY (CODPESSOA)
	REFERENCES PESSOA (CODPESSOA)
)


CREATE TABLE ENDERECO (
	CODENDERECO INT PRIMARY KEY,
	ENDERECORESIDENCIA NVARCHAR (250) UNIQUE,
	ENDERECOENTREGA NVARCHAR (250)
)


CREATE TABLE PESSOA_ENDERECO(
	CODCLIEND INT PRIMARY KEY IDENTITY (1,1),
	CODPESSOA INT,
	CODENDERECO INT,

	CONSTRAINT FK_PESSOAENDERECO_PESSOA FOREIGN KEY (CODPESSOA)
	REFERENCES PESSOA (CODPESSOA),

	CONSTRAINT FK_PESSOAENDERECO_ENDERECO FOREIGN KEY (CODENDERECO)
	REFERENCES ENDERECO (CODENDERECO)
)

CREATE TABLE PRODUTO (
	CODPRODUTO INT PRIMARY KEY IDENTITY (1,1),
	NOME NVARCHAR (100),
	VALOR DECIMAL (10,2),
	DESCRICAO NVARCHAR (250)
)

CREATE TABLE PEDIDO (
	CODPEDIDO INT PRIMARY KEY IDENTITY(1,1),
	DT DATETIME,
	FORMAPAGAMENTO NVARCHAR (100),
	CODPESSOA INT,
	CODVENDEDOR INT,

	CONSTRAINT FK_PEDIDO_PESSOA FOREIGN KEY (CODPESSOA)
	REFERENCES PESSOA (CODPESSOA),

	CONSTRAINT FK_PEDIDO_VENDEDOR FOREIGN KEY (CODVENDEDOR)
	REFERENCES VENDEDOR (CODVENDEDOR)
)

CREATE TABLE PRODUTO_PEDIDO(
	CODPROPED INT PRIMARY KEY IDENTITY (1,1),
	QUANTIDADE INT,
	VALORVENDA DECIMAL(10,2),
	CODPRODUTO INT,
	CODPEDIDO INT,

	CONSTRAINT FK_PRODPED_PRODUTO FOREIGN KEY (CODPRODUTO)
	REFERENCES PRODUTO (CODPRODUTO),

	CONSTRAINT FK_PRODPED_PEDIDO FOREIGN KEY (CODPEDIDO)
	REFERENCES PEDIDO (CODPEDIDO)
)

CREATE TABLE NOTAFISCAL( 
	CODNOTA INT PRIMARY KEY IDENTITY(1,1),
	CODPEDIDO INT,
	EMISSAO DATETIME,
	
	CONSTRAINT FK_NOTA_PEDIDO FOREIGN KEY (CODPEDIDO)
	REFERENCES PEDIDO (CODPEDIDO)
)
