CREATE TABLE CLIENTE (
  CODCLI INT PRIMARY KEY IDENTITY(1,1),
  NOMECLI  NVARCHAR(100)
)


CREATE TABLE EMPRESTIMO (
  CODEMP INT PRIMARY KEY IDENTITY(1,1),
  NOMEAG NVARCHAR(100),
  VALOR DECIMAL(10,2)
)


CREATE TABLE DEVEDOR(
  CODDEVEDOR INT PRIMARY KEY IDENTITY(1,1),
  CODCLI INT,
  CODEMP INT,
  
  CONSTRAINT FK_DEVEDOR_CLIENTE FOREIGN KEY (CODCLI)
  REFERENCES CLIENTE (CODCLI),
  
  CONSTRAINT FK_DEVEDOR_EMPRESTIMO FOREIGN KEY (CODEMP)
  REFERENCES EMPRESTIMO (CODEMP)
)


CREATE TABLE DEPOSITANTE(
  CODDEPOSITANTE INT PRIMARY KEY IDENTITY(1,1),
  CODCLI INT,
  NUMCONTA INT,
  
  CONSTRAINT FK_DEPOSITANTE_CLIENTE FOREIGN KEY (CODCLI)
  REFERENCES CLIENTE (CODCLI)

)


INSERT INTO CLIENTE (NOMECLI) VALUES
  ('Ana Lima'),
  ('Bruno Souza'),
  ('Carla Mendes'),
  ('Diego Costa'),
  ('Eva Rocha')


INSERT INTO EMPRESTIMO VALUES
  ('Santa Mônica', 1500.00),
  ('Santa Mônica', 3000.00),
  ('Centro', 2500.00),
  ('Centro', 800.00),
  ('Jardins',5000.00)


INSERT INTO DEVEDOR (CODCLI, CODEMP) VALUES
  (1, 1),  -- Ana Lima, Santa Mônica R$1500
  (2, 2),  -- Bruno Souza, Santa Mônica R$3000
  (4, 3)   -- Diego Costa, Centro R$2500


INSERT INTO DEPOSITANTE (CODCLI, NUMCONTA) VALUES
  (1, 1001),  -- Ana Lima
  (3, 1002),  -- Carla Mendes
  (5, 1003)   -- Eva Rocha

SELECT * FROM CLIENTE
SELECT * FROM EMPRESTIMO
SELECT * FROM DEVEDOR
SELECT * FROM DEPOSITANTE


-- EX1
SELECT * FROM EMPRESTIMO
WHERE NOMEAG = 'Santa Mônica'

--EX2
SELECT * FROM EMPRESTIMO
WHERE NOMEAG = 'Santa Mônica'
AND VALOR > 2000

--EX3
SELECT CODEMP, VALOR
FROM EMPRESTIMO

--EX4
SELECT CODEMP, VALOR
FROM EMPRESTIMO
WHERE NOMEAG = 'Centro'

--EX5
SELECT NOMECLI
FROM CLIENTE
WHERE CODCLI IN (
  SELECT CODCLI FROM DEPOSITANTE
  UNION
  SELECT CODCLI FROM DEVEDOR
)

--EX6
SELECT NOMECLI
FROM CLIENTE
WHERE CODCLI IN (
  SELECT CODCLI FROM DEPOSITANTE
)
AND CODCLI NOT IN (
  SELECT CODCLI FROM DEVEDOR
)
  



  
  
