--CRIAÇÃO TABELAS NORMALIZADAS


CREATE TABLE DEPARTAMENTO(
	IDDEPARTAMENTO INT PRIMARY KEY IDENTITY(1,1),
	NOME NVARCHAR (100),
	DESCRICAO NVARCHAR(200)
)

CREATE TABLE CARGO(
	IDCARGO INT PRIMARY KEY IDENTITY(1,1),
	NOME NVARCHAR(100),
	DESCRICAO NVARCHAR(200)
)


CREATE TABLE SALARIO(
	SALARIOBASE DECIMAL(10,2),
	VALORHREXTRA DECIMAL (10,2),
	TOTALHREXTRA DECIMAL(10,2),
	DESCONTOINSS DECIMAL(10,2),
	SALARIOLIQUIDO DECIMAL(10,2)
)

CREATE TABLE FUNCIONARIO(
	IDFUNC INT PRIMARY KEY IDENTITY(1,1),
	MATRICULAFUNC INT,
	NOMEFUNC NVARCHAR(150),
	CPF NVARCHAR(20),
	IDDEPARTAMENTO INT,
	IDGERENTE INT,
	IDCARGO INT,

	CONSTRAINT FK_FUNC_DEP FOREIGN KEY(IDDEPARTAMENTO)
	REFERENCES DEPARTAMENTO(IDDEPARTAMENTO),

	CONSTRAINT FK_FUNC_GERENTE FOREIGN KEY(IDGERENTE)
	REFERENCES GERENTE(IDGERENTE),

	CONSTRAINT FK_FUNC_CARGO FOREIGN KEY (IDCARGO)
	REFERENCES CARGO (IDCARGO)


)

CREATE TABLE GERENTE(
	IDGERENTE INT PRIMARY KEY IDENTITY(1,1),
	IDFUNC INT,

	CONSTRAINT FK_GERENTE_FUNC FOREIGN KEY (IDFUNC)
	REFERENCES FUNCIONARIO (IDFUNC)
)


CREATE TABLE FOLHAPAGAMENTO(
	CODFOLHA INT PRIMARY KEY IDENTITY(1,1),
	MES NVARCHAR(20)
)

