CREATE TABLE CATEGORIAS(
	IDCATEGORIA INT PRIMARY KEY IDENTITY(1,1),
	DESCCATEGORIA NVARCHAR (200)
)

CREATE TABLE PRODUTOS(
	IDPROD INT PRIMARY KEY IDENTITY(1,1),
	DESCPROD NVARCHAR(200),
	PRECO DECIMAL(7,2),
	IDCATEGORIA INT,

	FOREIGN KEY (IDCATEGORIA) REFERENCES CATEGORIAS (IDCATEGORIA)
)

CREATE TABLE VENDAS (
	IDVENDA INT PRIMARY KEY IDENTITY(1,1),
	IDPROD INT,
	QTD INT,
	DTVENDA DATE,

	FOREIGN KEY (IDPROD) REFERENCES PRODUTOS (IDPROD)
)

INSERT INTO CATEGORIAS VALUES
('ELETRONICOS'), ('ESCRITORIO')
SELECT*FROM CATEGORIAS

INSERT INTO PRODUTOS VALUES
('MOUSE SEM FIO', 85.00, 2),
('MONITOR 24 POL', 980.00, 1),
('TECLADO', 200.00, 2)
SELECT*FROM PRODUTOS

INSERT INTO VENDAS VALUES
(1,2, GETDATE()),
(2,1, GETDATE()),
(3,3, GETDATE())


CREATE VIEW VW_VENDAS AS(
SELECT
	V.IDVENDA,
	P.DESCPROD,
	C.DESCCATEGORIA,
	V.QTD,
	(V.QTD * P.PRECO) AS VALOR_TOTAL,
	V.DTVENDA

FROM
VENDAS V
INNER JOIN PRODUTOS P ON V.IDPROD=P.IDPROD
INNER JOIN CATEGORIAS C ON P.IDCATEGORIA = C.IDCATEGORIA

)

SELECT * FROM VW_VENDAS
WHERE DESCCATEGORIA = 'ESCRITORIO'

ALTER VIEW
