CREATE TABLE CLIENTES (
	CODCLIENTE INT PRIMARY KEY IDENTITY(1,1),
	NOME NVARCHAR(200)
)

CREATE TABLE PRODUTOS(
	CODPRODUTO INT PRIMARY KEY IDENTITY(1,1),
	DESCRICAO NVARCHAR (200),
	PRECO DECIMAL (7,2),
	CODCATEGORIA INT
)

CREATE TABLE CATEGORIA (
	CODCATEGORIA INT PRIMARY KEY IDENTITY(1,1),
	DESCRICAO NVARCHAR (100)
)

CREATE TABLE PEDIDO(
	CODPEDIDO INT PRIMARY KEY IDENTITY(1,1),
	CODCLIENTE INT,
	CODPRODUTO INT,
	QTD INT
)
  
--ALTERANDO AS TABELAS, ADICIONANDO AS FK
ALTER TABLE PRODUTOS
ADD CONSTRAINT FK_PRODCAT FOREIGN KEY (CODCATEGORIA)
REFERENCES CATEGORIA (CODCATEGORIA)

ALTER TABLE PEDIDO
ADD CONSTRAINT FK_PEDCLI FOREIGN KEY (CODCLIENTE)
REFERENCES CLIENTES (CODCLIENTE)

ALTER TABLE PEDIDO
ADD CONSTRAINT FK_PEDPROD FOREIGN KEY (CODPRODUTO)
REFERENCES PRODUTOS (CODPRODUTO)

--INSERINDO VALORES
INSERT INTO CLIENTES VALUES
('WARNER'), ('ANA CLARA'), ('JOAO DA SILVA'), ('MARIA JOAQUINA'), ('PELE'); 

INSERT INTO CATEGORIA VALUES
('ALIMENTOS'), ('ELETRONICOS'), ('MEDICAMENTOS')
  

SELECT * FROM CATEGORIA
  

INSERT INTO PRODUTOS VALUES
('ARROZ', 23, 1), ('FEIJAO', 12, 1), ('MACARRAO', 6, 1),
('DIPIRONA', 2, 3), ('OMEPRAZOL',6, 3), ('DORFLEX', 7, 3),
('CELULAR', 1000, 2), ('TV', 800, 2), ('RADIO', 200, 2)
  

SELECT * FROM PRODUTOS
  

INSERT INTO PEDIDO VALUES
(1,1,1), (1,4,2), (1,5,1), 
(2,8,1), (3,9,1), (5,6,3), (5,3,1)
  

SELECT * FROM PEDIDO
  

SELECT P.DESCRICAO PRODUTO, P.PRECO, C.DESCRICAO CATEGORIA
FROM PRODUTOS P 
INNER JOIN CATEGORIA C ON P.CODCATEGORIA=C.CODCATEGORIA --TRAZ TODAS AS TABELAS QUE FORAM VINCULADAS


SELECT  C.DESCRICAO CATEGORIA, COUNT(P.CODPRODUTO) AS QUANTIDADE --QUANTOS PRODUTOS EM CADA CATEGORIA
FROM PRODUTOS P 
INNER JOIN CATEGORIA C ON P.CODCATEGORIA=C.CODCATEGORIA --TODOS QUE ESTIVEREM NOS DOIS, INTERSECÇÃO
GROUP BY C.DESCRICAO


INSERT INTO CATEGORIA VALUES
('ESPORTE')

SELECT  C.DESCRICAO CATEGORIA, COUNT(P.CODPRODUTO) AS QUANTIDADE 
FROM PRODUTOS P 
RIGHT JOIN CATEGORIA C ON P.CODCATEGORIA=C.CODCATEGORIA 
GROUP BY C.DESCRICAO

INSERT INTO CATEGORIA VALUES
('BEBIDAS')

--MOSTRAR O PEDIDO DO CLIENTE
SELECT CL.NOME CLIENTE, PR.DESCRICAO PRODUTO, PR.PRECO, PE.QTD, CA.DESCRICAO CATEGORIA,
PR.PRECO VLRUNIT, PE.QTD, PR.PRECO*PE.QTD VLRTOTAL
FROM CLIENTES CL
INNER JOIN PEDIDO PE ON CL.CODCLIENTE=PE.CODCLIENTE
INNER JOIN PRODUTOS PR ON PE.CODPRODUTO=PR.CODPRODUTO
INNER JOIN CATEGORIA CA ON PR.CODCATEGORIA=CA.CODCATEGORIA


--QUAIS CATEGORIAS VENDERAM MAIS
SELECT 
CA.DESCRICAO CATEGORIA, COUNT(PR.CODPRODUTO)
FROM PEDIDO PE
INNER JOIN PRODUTOS PR ON PE.CODPRODUTO=PR.CODPRODUTO
INNER JOIN CATEGORIA CA ON PR.CODCATEGORIA=CA.CODCATEGORIA
GROUP BY CA.DESCRICAO
ORDER BY 2 DESC --DESC: ORDENA DO MAIOR PARA O MENOR


--QUANTOS PRODUTOS CADA CLIENTE COMPROU POR CATEGPRIA
SELECT CL.NOME CLIENTE, CA.DESCRICAO CATEGORIA,
COUNT(PR.CODPRODUTO) AS QUANTIDADE
FROM CLIENTES CL
INNER JOIN PEDIDO PE ON CL.CODCLIENTE=PE.CODCLIENTE
INNER JOIN PRODUTOS PR ON PE.CODPRODUTO=PR.CODPRODUTO
INNER JOIN CATEGORIA CA ON PR.CODCATEGORIA=CA.CODCATEGORIA
GROUP BY CL.NOME, CA.DESCRICAO



