--PARTE 1: CRIAR TABELAS
CREATE TABLE CADEIA (
	IDCADEIA INT PRIMARY KEY IDENTITY(1,1),
	NOME NVARCHAR (200),
	CIDADE NVARCHAR (200)
)


CREATE TABLE MAGAZINE (
	IDMAGAZINE INT PRIMARY KEY IDENTITY(1,1),
	NOME NVARCHAR (200),
	GERENTE NVARCHAR(100),
	IDCADEIA INT, 

	CONSTRAINT FK_MAGAZINE_CADEIA FOREIGN KEY (IDCADEIA)
	REFERENCES CADEIA (IDCADEIA)
)

CREATE TABLE PRODUTO (
	IDPRODUTO INT PRIMARY KEY IDENTITY(1,1),
	NOME NVARCHAR (150),
	UNIMED NVARCHAR (10)
)

CREATE TABLE VENDA (
	IDVENDA INT PRIMARY KEY IDENTITY(1,1),
	IDMAGAZINE INT,
	IDPRODUTO INT,
	QUANTIDADE INT,

	CONSTRAINT FK_VENDA_MAGAZINE FOREIGN KEY (IDMAGAZINE)
	REFERENCES MAGAZINE (IDMAGAZINE),

	CONSTRAINT FK_VENDA_PRODUTO FOREIGN KEY (IDPRODUTO)
	REFERENCES PRODUTO (IDPRODUTO)
)

--PARTE 2: INSERIR 2 REGISTROS EM CADA TABELA
INSERT INTO CADEIA VALUES
('CADEIA1','CRUZEIRO'),
('CADEIA2','LORENA')

SELECT * FROM CADEIA

INSERT INTO  MAGAZINE VALUES
('MAGAZINE1','SARAH', 1), 
('MAGAZINE2', 'MARIA', 2)

SELECT * FROM MAGAZINE

INSERT INTO PRODUTO VALUES
('CELULAR', 'UN'),
('ARROZ', 'KG')

SELECT * FROM PRODUTO

INSERT INTO VENDA VALUES
(1,1,10),
(2,2,5)

SELECT *FROM VENDA

ALTER TABLE VENDA
ADD DATEVENDA DATE

UPDATE VENDA SET DATEVENDA=GETDATE()
WHERE IDVENDA=1

UPDATE VENDA SET DATEVENDA=GETDATE()
WHERE IDVENDA=2

--PASSO3: INSERIR REGISTRO NA TABELA PRODUTO
INSERT INTO PRODUTO VALUES
('CALÇA JEANS', 'UN')

--PASSO 4: ALTERAR DESCRIÇÃO
UPDATE PRODUTO SET NOME='CAMISA DE ALGODÃO'
WHERE IDPRODUTO=3

--PASSO 5: DELETE PRODUTO
DELETE FROM PRODUTO
WHERE IDPRODUTO = 3

--PASSO 6: CRIAR NOVA TABELA ESTADOS
CREATE TABLE 

