CREATE TABLE CONTA (
	CODCONTA INT PRIMARY KEY IDENTITY(1,1),
	SALDO DECIMAL (7,2)
	)

CREATE TABLE MOVIMENTACAO(
	CODMOV INT PRIMARY KEY IDENTITY (1,1),
	CODCONTA INT,
	TIPOMOV NVARCHAR(1),
	VALORMOV DECIMAL (7,2),
	DATAMOV DATE
)

ALTER TABLE MOVIMENTACAO
ADD CONSTRAINT FK_MOVIMENTACAO_CONTA FOREIGN KEY (CODCONTA)
REFERENCES CONTA (CODCONTA)

INSERT INTO CONTA (SALDO) VALUES (0)

SELECT * FROM CONTA



ALTER  PROCEDURE ATUALIZA_SALDO (
	@CODCONTA INT,
	@VALORMOV DECIMAL (7,2),
	@TIPOMOV NVARCHAR(1)
) AS

BEGIN
	DECLARE @SALDO DECIMAL(7,2)

	IF(EXISTS(SELECT CODCONTA FROM CONTA WHERE CODCONTA=@CODCONTA))
	BEGIN
		IF (@TIPOMOV = 'D')
		BEGIN
			-- INSERE MOVIMENTACAO
			INSERT INTO MOVIMENTACAO (CODCONTA, TIPOMOV, VALORMOV, DATAMOV)
			VALUES (@CODCONTA, @TIPOMOV, @VALORMOV, GETDATE());
			--ATUALIZA SALDO NA CONTA
			UPDATE CONTA SET SALDO = (SELECT SALDO + @VALORMOV FROM CONTA WHERE CODCONTA=@CODCONTA) WHERE CODCONTA=@CODCONTA;
	END

		ELSE IF (@TIPOMOV='S')
		BEGIN

			SELECT @SALDO = SALDO FROM CONTA WHERE CODCONTA=@CODCONTA;

			IF (@SALDO<@VALORMOV)
				SELECT 'SALDO INSUFICIENTE PARA SAQUE! SALDO ATUAL: ' + CONVERT(NVARCHAR, @SALDO)
			ELSE

			BEGIN
			-- INSERE MOVIMENTACAO
			INSERT INTO MOVIMENTACAO (CODCONTA, TIPOMOV, VALORMOV, DATAMOV)
			VALUES (@CODCONTA, @TIPOMOV, @VALORMOV*-1, GETDATE());
			--ATUALIZA SALDO NA CONTA
			UPDATE CONTA SET SALDO = (SELECT SALDO - @VALORMOV FROM CONTA WHERE CODCONTA=@CODCONTA) WHERE CODCONTA=@CODCONTA;
		END
	END


	ELSE
		SELECT 'OPCAO INVALIDA!'
END


ELSE
	SELECT 'CONTA INEXISTENTE'
END


INSERT INTO MOVIMENTACAO (CODCONTA, TIPOMOV, VALORMOV, DATAMOV)
VALUES(1, 'S', -100, GETDATE())

EXEC ATUALIZA_SALDO @CODCONTA=1, @VALORMOV=100, @TIPOMOV = 'D'

SELECT *FROM CONTA
SELECT CODCONTA, SUM(VALORMOV) AS VALORTOTAL FROM MOVIMENTACAO
GROUP  BY CODCONTA


SELECT * FROM MOVIMENTACAO
SELECT * FROM CONTA

EXEC ATUALIZA_SALDO @CODCONTA=1, @VALORMOV=100, @TIPOMOV = 'S'
EXEC ATUALIZA_SALDO @CODCONTA=1, @VALORMOV=2000, @TIPOMOV = 'S'

--CRIAR UMA NOVA PROCEDURE PARA EXCLUIR UMA MOVIMENTAÇÃO E ATUALIZAR DE ACORDO COM  O QUE EXCLUIU

CREATE PROCEDURE EXCLUI_ATUALIZA(
	
