-- DESENVOLVIMENTO DE TIGGER--

CREATE TABLE CONTA(
IDCONTA INT PRIMARY KEY IDENTITY(1,1),
SALDO DECIMAL(7,2),
)

CREATE TABLE MOVIMENTACAO(
IDMOV INT PRIMARY KEY IDENTITY(1,1),
IDCONTA INT,
TIPOMOV NVARCHAR(1),
VALORMOV DECIMAL(7,2),
DATAMOV DATE
)

ALTER TABLE MOVIMENTACAO
ADD CONSTRAINT FK_MOV FOREIGN KEY
(IDCONTA) REFERENCES CONTA (IDCONTA)

ALTER TRIGGER TGR_MOV_INS
ON MOVIMENTACAO --ONDE VAI SER APLICADA, SERA CRIADA BASEADA NA TABELA MOV
FOR INSERT
AS
BEGIN
	DECLARE
	@VALOR DECIMAL(7,2),
	@IDCONTA INT,
	@TIPOMOV NVARCHAR(1)

	SELECT @IDCONTA=IDCONTA, @VALOR=VALORMOV, @TIPOMOV=TIPOMOV FROM INSERTED --RECUPERAR VALOR DAS VARIAVEIS

	UPDATE CONTA SET SALDO = SALDO + @VALOR
	WHERE IDCONTA=@IDCONTA

	INSERT INTO LOGS (DATAEX, TIPOMOV, VALORMOV)
	VALUES(GETDATE(), 'D', 100)

END


INSERT INTO CONTA (SALDO) VALUES (0)

SELECT * FROM CONTA
SELECT * FROM MOVIMENTACAO
SELECT * FROM LOGS

INSERT INTO MOVIMENTACAO(TIPOMOV, VALORMOV, DATAMOV, IDCONTA)
VALUES('D', 100, GETDATE(), 1)

CREATE TABLE LOGS(
	IDLOG INT PRIMARY KEY IDENTITY(1,1),
	DATAEX DATE,
	TIPOMOV NVARCHAR(1),
	VALORMOV DECIMAL(7,2)
)


--BEGIN TRANSACTION
--ROLLBACK TRANSACTION
